export const PREVIEW_TICKET_REFRESH_MARGIN_MS = 30_000;

export const PREVIEW_TICKET_FALLBACK_REFRESH_MS = 4 * 60 * 1_000;

export const PREVIEW_TICKET_RETRY_MS = 5_000;

export const PREVIEW_TICKET_MAX_AUTO_RETRIES = 2;
