import { PROMPT_REPLY_SYNC_WATCHDOG_DELAY_MS } from "@modules/dashboard/model/liveUpdates/helpers";

export const EXTERNAL_FORCE_STOP_CONFIRMATION_GRACE_MS = 20_500;
export const PROMPT_REPLY_WATCHDOG_HARD_TIMEOUT_MS = 15 * 60_000;
export const PROMPT_REPLY_WATCHDOG_RETRY_MS = PROMPT_REPLY_SYNC_WATCHDOG_DELAY_MS;
export const PROMPT_REPLY_WATCHDOG_TERMINAL_GRACE_MS = 15_000;
