import { PROMPT_REPLY_SYNC_WATCHDOG_DELAY_MS } from "@modules/dashboard/model/liveUpdates/helpers";

export const EXTERNAL_FORCE_STOP_CONFIRMATION_GRACE_MS = 20_500;
export const PROMPT_TRANSCRIPT_SYNC_RETRY_MS = PROMPT_REPLY_SYNC_WATCHDOG_DELAY_MS;
export const PROMPT_TRANSCRIPT_SYNC_WINDOW_MS = 15_000;
