export const CODEX_CHAT_MESSAGE_LINE_DETECTION_MAX_BYTES = 256 * 1024;
export const CODEX_CHAT_MESSAGE_LINE_READ_MULTIPLIER = 4;
export const CODEX_CHAT_MESSAGE_TAIL_MAX_READ_BYTES = 16 * 1024 * 1024;
export const CODEX_TRANSCRIPT_EXPANDED_TAIL_READ_BYTES = 4 * 1024 * 1024;
export const CODEX_TRANSCRIPT_INDEXED_LINE_HINT_BYTES = 8192;
export const CODEX_TRANSCRIPT_LINE_OFFSET_BLOCK_SIZE = 256;
export const CODEX_TRANSCRIPT_TAIL_READ_BYTES = 512 * 1024;
export const CODEX_TRANSCRIPT_TAIL_WINDOW_BACKTRACK_BYTES = 64 * 1024 * 1024;
