import type { AgentBrowserShellProps } from "@modules/dashboard/shell/AgentBrowserShell";
import type { ManagedSessionShellProps } from "@modules/dashboard/shell/ManagedSessionShell";
import type { SecondaryToolsShellProps } from "@modules/dashboard/shell/SecondaryToolsShell";

import { buildAgentCliRuntimeRows } from "./agentCliRuntimeRows";
import type { DashboardShellSectionProps } from "./types";

export function buildAgentBrowserShellProps({
  agentSessionsHasMore,
  agentSessionsLoadState,
  agentSessionsQuery,
  agentSessionsTotalCountLabel,
  attachedManagedSessionId,
  attachedManagedSessionInfo,
  effectiveSelectedAgentSessionId,
  effectiveSelectedSourceId,
  filteredAgentSessions,
  isAgentSessionLoading,
  isBootstrapping,
  isOpeningSelectedAgentSession,
  managedSessions,
  onAttachSelectedAgentSession,
  onClearAgentSessionSelection,
  onLoadMoreAgentSessions,
  onMarkAgentSessionReviewed,
  onOpenManagedSession,
  onOpenLocalLlmChat,
  onReloadAgentSessions,
  onSearchAgentSessions,
  onSelectAgentSession,
  onSelectSource,
  pendingChatPrompt,
  readyForReviewAgentSessionIds,
  runtimes,
  selectedAgentSession,
  sourceCards,
  workspaces
}: DashboardShellSectionProps): AgentBrowserShellProps {
  return {
    totalAgentSessionsCount: agentSessionsTotalCountLabel,
    agentSessions: filteredAgentSessions,
    agentSessionsHasMore,
    agentSessionsLoadState,
    agentSessionsQuery,
    runtimes,
    workspaces,
    readyForReviewAgentSessionIds,
    managedSessions,
    pendingChatPrompt,
    sourceCards,
    selectedSourceId: effectiveSelectedSourceId,
    selectedAgentSessionId: effectiveSelectedAgentSessionId,
    selectedAgentSession,
    isAgentSessionLoading,
    attaching: isOpeningSelectedAgentSession,
    attachedManagedSessionId,
    attachedManagedSessionInfo,
    isBootstrapping,
    onSelectSource,
    onLoadMoreAgentSessions,
    onReloadAgentSessions,
    onSearchAgentSessions,
    onMarkAgentSessionReviewed,
    onSelectAgentSession,
    onClearAgentSessionSelection,
    onAttachAgentSession: onAttachSelectedAgentSession,
    onOpenManagedSession,
    onOpenLocalLlmChat
  };
}

export function buildManagedSessionShellProps({
  activeTab,
  agentSessions,
  agentTranscriptHasMoreById,
  effectiveSelectedSessionId,
  initialManagedSessionLoadState,
  isBootstrapping,
  isInterruptingPrompt,
  immediateInterruptPrompt,
  isTakenOverAgentSessionLoading,
  isWaitingForChatReply,
  liveUpdatesConnection,
  managedSessions,
  onChangePreviewPort,
  onChangePreviewNetworkMode,
  onExitSession,
  onHydrateAgentSessionChanges,
  onInterruptPrompt,
  onHydrateAgentSessionTranscriptEntries,
  onLoadMoreAgentSessionTranscript,
  onRefreshGit,
  onRetryInitialManagedSessionLoad,
  onSelectManagedSession,
  onSelectSessionTab,
  onSendInput,
  onSetPreview,
  onStopPreview,
  onStopAndExitSession,
  onStopSession,
  pendingChatPrompt,
  previewPort,
  selectedSession,
  takenOverAgentSession
}: DashboardShellSectionProps): ManagedSessionShellProps {
  return {
    agentSessions,
    managedSessions,
    selectedSessionId: effectiveSelectedSessionId,
    selectedSession,
    takenOverAgentSession,
    agentTranscriptHasMoreById,
    isTakenOverAgentSessionLoading,
    liveUpdatesConnection,
    activeTab,
    previewPort,
    isBootstrapping,
    sessionLoadError:
      initialManagedSessionLoadState.kind === "error"
        ? initialManagedSessionLoadState.message
        : null,
    pendingChatPrompt,
    isWaitingForChatReply,
    isInterruptingPrompt,
    immediateInterruptPrompt,
    onSelectSession: onSelectManagedSession,
    onSelectTab: onSelectSessionTab,
    onSendInput,
    onHydrateAgentSessionChanges,
    onHydrateAgentSessionTranscriptEntries,
    onLoadMoreAgentSessionTranscript,
    onInterruptPrompt,
    onStopSession,
    onStopAndExitSession,
    onExitSession,
    onRefreshGit,
    onRetrySessionLoad: onRetryInitialManagedSessionLoad,
    onChangePreviewPort,
    onChangePreviewNetworkMode,
    onSetPreview,
    onStopPreview
  };
}

export function buildSecondaryToolsShellProps({
  agentSessions,
  canOpenNativeDialogs,
  command,
  isBootstrapping,
  loading,
  onAddWorkspace,
  onChangeCommand,
  onChangeWorkspacePath,
  onPickWorkspace,
  onSelectWorkspace,
  onStartSession,
  pickingWorkspace,
  runtimes,
  selectedWorkspaceId,
  sourceCards,
  workspacePath,
  workspaces
}: DashboardShellSectionProps): SecondaryToolsShellProps {
  return {
    agentCliRuntimes: buildAgentCliRuntimeRows(agentSessions, sourceCards, runtimes),
    workspacePath,
    loading,
    pickingWorkspace,
    canOpenNativeDialogs,
    selectedWorkspaceId,
    workspaces,
    command,
    runtimes,
    isBootstrapping,
    compact: true,
    presentation: "list",
    onChangeWorkspacePath,
    onPickWorkspace,
    onAddWorkspace,
    onSelectWorkspace,
    onChangeCommand,
    onStartSession
  };
}
